### PR TITLE
Infinite Loading Animation Fix

### PR DESCRIPTION
**Pull request by suryadip2008**
**_Reproduction steps:_**

1. Ensure you are using the latest beta version of Snapchat with the "Simple Snapchat" feature on
2. In SE Extended settings, navigate to "hide story suggestions "

3. **Ensure that you have enabled the option to hide suggested friend stories** (Otherwise the fix may not work)

4. Open Snapchat and go to the chat page (where stories are now located at the top)
5. Observe the area where friend suggestions would normally appear
6. Note that the issue has been resolved
7.Wait for a friend to post a story or find a friend who has an active story
8.Observe that the infinite loading animation issue has been resolved.

### CODE REVIEW

**Comment by bocajthomas** [comment]
@suryadip2008 for CustomTextFont , please make a new branch then add then pull that way 
Infinite Loading Animation Fix can be a seperate commit

**Comment by suryadip2008** [comment]
> @suryadip2008 for CustomTextFont , please make a new branch then add then pull that way Infinite Loading Animation Fix can be a seperate commit, I will also review and test this pull request in a week's time.

I have currently no plans to continue developing CustomTextFont(as I was encountering many errors, and I don't have my main device rn), that's why I removed it.
As for the Infinite Loading Animation Fix, I have created this pull request.

**Comment by suryadip2008** [comment]
Pull request closed as issue still persists.

**Comment by bocajthomas** [comment]
> Pull request closed as issue still persists.

Repull when your ready.

**Pull request closed without merging**
